name: Terraform Okta Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Step 3: Set up secrets as environment variables
      - name: Export environment secrets
        run: |
          echo "OKTA_API_TOKEN=${{ secrets.OKTA_API_TOKEN }}" >> $GITHUB_ENV
          echo "OKTA_ORG_NAME=${{ secrets.OKTA_ORG_NAME }}" >> $GITHUB_ENV
          echo "OKTA_BASE_URL=${{ secrets.OKTA_BASE_URL }}" >> $GITHUB_ENV

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Terraform Plan
        # Optional: show output for debugging in PRs
      - name: Terraform Plan
        run: terraform plan

      # Step 7: Terraform Apply — only if it's a push to master
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve
