name: Terraform Okta Integration (prod)

on:
  push:
    branches: [ main ]   # change to your default branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_okta_api_token: ${{ secrets.OKTA_API_TOKEN }}
      TF_VAR_okta_org_name:  ${{ secrets.OKTA_ORG_NAME }}
      TF_VAR_okta_base_url:  ${{ secrets.OKTA_BASE_URL }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Checkout State Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/iam_terraform_state
          path: state-repo
          token: ${{ secrets.STATE_REPO_PAT }}
          fetch-depth: 0

      - name: Restore State
        run: |
          mkdir -p state-repo/prod
          cp -f state-repo/prod/terraform.tfstate terraform.tfstate || true
          cp -f state-repo/prod/.terraform.lock.hcl .terraform.lock.hcl || true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply (prod)
        run: terraform apply -auto-approve -input=false

      - name: Backup State
        run: |
          mkdir -p state-repo/prod
          cp -f terraform.tfstate state-repo/prod/terraform.tfstate
          cp -f .terraform.lock.hcl state-repo/prod/.terraform.lock.hcl
          cd state-repo
          git add -A
          git commit -m "Backup prod state at $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
